chunking_config:
  chunk_overlap_tokens: 256
  chunk_size_tokens: 1024
  class_path: cookbook.config.data_pipeline.recursive_text_splitter.RecursiveTextSplitterChunkingConfig
  embedding_model_endpoint: databricks-gte-large-en
class_path: cookbook.config.data_pipeline.DataPipelineConfig
output:
  chunked_docs_table: shared.cookbook_langgraph_udhay.test_product_docs_docs_chunked__v2
  class_path: cookbook.config.data_pipeline.data_pipeline_output.DataPipelineOuputConfig
  parsed_docs_table: shared.cookbook_langgraph_udhay.test_product_docs_docs__v2
  vector_index: shared.cookbook_langgraph_udhay.test_product_docs_docs_chunked_index__v2
  vector_search_endpoint: one-env-shared-endpoint-15
source:
  class_path: cookbook.config.data_pipeline.uc_volume_source.UCVolumeSourceConfig
  uc_catalog_name: shared
  uc_schema_name: cookbook_langgraph_udhay
  uc_volume_name: product_docs
  volume_path: /Volumes/shared/cookbook_langgraph_udhay/product_docs
  volume_uc_fqn: shared.cookbook_langgraph_udhay.product_docs
