# Source: https://github.com/executablebooks/cookiecutter-jupyter-book/blob/main/.github/workflows/deploy.yml
name: deploy-book

on:
  # Trigger the deploy on push to main branch
  push:
    branches:
      - main

env:
  BASE_URL: /${{ github.event.repository.name }}

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

      # Install dependencies
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install -r dev/build_requirements.txt
      # Build the example book
      - name: Build book
        run: |
          jupyter-book build genai_cookbook/
          cp ./genai_cookbook/10-min-demo/mosaic-ai-agents-demo-dbx-notebook.html ./genai_cookbook/_build/html/10-min-demo/mosaic-ai-agents-demo-dbx-notebook.html
      # Upload the book's HTML as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "genai_cookbook/_build/html"
      # Deploy the book's HTML to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
